# Generated by Django 6.0.1 on 2026-04-02 14:50

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='URL do servidor Evolution API (ex: http://meuservidor.com)')),
                ('api_key', usuarios.models.EncryptedCharField(help_text='API Key da instância Evolution API')),
                ('instancia', models.CharField(help_text='Nome da instância no Evolution API', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
