# Generated by Django 6.0.1 on 2026-04-08 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_consentimentolgpd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cnj', models.CharField(max_length=30, verbose_name='Número CNJ')),
                ('tribunal', models.CharField(choices=[('tst', 'TST — Tribunal Superior do Trabalho'), ('tse', 'TSE — Tribunal Superior Eleitoral'), ('stj', 'STJ — Superior Tribunal de Justiça'), ('stm', 'STM — Superior Tribunal Militar'), ('trf1', 'TRF-1ª Região'), ('trf2', 'TRF-2ª Região'), ('trf3', 'TRF-3ª Região'), ('trf4', 'TRF-4ª Região'), ('trf5', 'TRF-5ª Região'), ('trf6', 'TRF-6ª Região'), ('tjac', 'TJAC — Acre'), ('tjal', 'TJAL — Alagoas'), ('tjam', 'TJAM — Amazonas'), ('tjap', 'TJAP — Amapá'), ('tjba', 'TJBA — Bahia'), ('tjce', 'TJCE — Ceará'), ('tjdft', 'TJDFT — Distrito Federal'), ('tjes', 'TJES — Espírito Santo'), ('tjgo', 'TJGO — Goiás'), ('tjma', 'TJMA — Maranhão'), ('tjmg', 'TJMG — Minas Gerais'), ('tjms', 'TJMS — Mato Grosso do Sul'), ('tjmt', 'TJMT — Mato Grosso'), ('tjpa', 'TJPA — Pará'), ('tjpb', 'TJPB — Paraíba'), ('tjpe', 'TJPE — Pernambuco'), ('tjpi', 'TJPI — Piauí'), ('tjpr', 'TJPR — Paraná'), ('tjrj', 'TJRJ — Rio de Janeiro'), ('tjrn', 'TJRN — Rio Grande do Norte'), ('tjro', 'TJRO — Rondônia'), ('tjrr', 'TJRR — Roraima'), ('tjrs', 'TJRS — Rio Grande do Sul'), ('tjsc', 'TJSC — Santa Catarina'), ('tjse', 'TJSE — Sergipe'), ('tjsp', 'TJSP — São Paulo'), ('tjto', 'TJTO — Tocantins'), ('trt1', 'TRT-1ª Região'), ('trt2', 'TRT-2ª Região'), ('trt3', 'TRT-3ª Região'), ('trt4', 'TRT-4ª Região'), ('trt5', 'TRT-5ª Região'), ('trt6', 'TRT-6ª Região'), ('trt7', 'TRT-7ª Região'), ('trt8', 'TRT-8ª Região'), ('trt9', 'TRT-9ª Região'), ('trt10', 'TRT-10ª Região'), ('trt11', 'TRT-11ª Região'), ('trt12', 'TRT-12ª Região'), ('trt13', 'TRT-13ª Região'), ('trt14', 'TRT-14ª Região'), ('trt15', 'TRT-15ª Região'), ('trt16', 'TRT-16ª Região'), ('trt17', 'TRT-17ª Região'), ('trt18', 'TRT-18ª Região'), ('trt19', 'TRT-19ª Região'), ('trt20', 'TRT-20ª Região'), ('trt21', 'TRT-21ª Região'), ('trt22', 'TRT-22ª Região'), ('trt23', 'TRT-23ª Região'), ('trt24', 'TRT-24ª Região'), ('tre-ac', 'TRE-AC — Acre'), ('tre-al', 'TRE-AL — Alagoas'), ('tre-am', 'TRE-AM — Amazonas'), ('tre-ap', 'TRE-AP — Amapá'), ('tre-ba', 'TRE-BA — Bahia'), ('tre-ce', 'TRE-CE — Ceará'), ('tre-dft', 'TRE-DF — Distrito Federal'), ('tre-es', 'TRE-ES — Espírito Santo'), ('tre-go', 'TRE-GO — Goiás'), ('tre-ma', 'TRE-MA — Maranhão'), ('tre-mg', 'TRE-MG — Minas Gerais'), ('tre-ms', 'TRE-MS — Mato Grosso do Sul'), ('tre-mt', 'TRE-MT — Mato Grosso'), ('tre-pa', 'TRE-PA — Pará'), ('tre-pb', 'TRE-PB — Paraíba'), ('tre-pe', 'TRE-PE — Pernambuco'), ('tre-pi', 'TRE-PI — Piauí'), ('tre-pr', 'TRE-PR — Paraná'), ('tre-rj', 'TRE-RJ — Rio de Janeiro'), ('tre-rn', 'TRE-RN — Rio Grande do Norte'), ('tre-ro', 'TRE-RO — Rondônia'), ('tre-rr', 'TRE-RR — Roraima'), ('tre-rs', 'TRE-RS — Rio Grande do Sul'), ('tre-sc', 'TRE-SC — Santa Catarina'), ('tre-se', 'TRE-SE — Sergipe'), ('tre-sp', 'TRE-SP — São Paulo'), ('tre-to', 'TRE-TO — Tocantins'), ('tjmmg', 'TJM-MG — Tribunal de Justiça Militar de Minas Gerais'), ('tjmrs', 'TJM-RS — Tribunal de Justiça Militar do Rio Grande do Sul'), ('tjmsp', 'TJM-SP — Tribunal de Justiça Militar de São Paulo'), ('outro', 'Outro')], max_length=20, verbose_name='Tribunal')),
                ('tribunal_outro', models.CharField(blank=True, help_text='Preencha apenas se selecionou "Outro" acima.', max_length=100, verbose_name='Tribunal (outro)')),
                ('vara', models.CharField(blank=True, max_length=150, verbose_name='Vara')),
                ('comarca', models.CharField(blank=True, max_length=150, verbose_name='Comarca')),
                ('tipo_acao', models.CharField(blank=True, max_length=150, verbose_name='Tipo de ação')),
                ('polo_ativo', models.CharField(blank=True, max_length=255, verbose_name='Polo ativo')),
                ('polo_passivo', models.CharField(blank=True, max_length=255, verbose_name='Polo passivo')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado')], default='ativo', max_length=15, verbose_name='Status')),
                ('data_distribuicao', models.DateField(blank=True, null=True, verbose_name='Data de distribuição')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor da causa (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='usuarios.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
                'unique_together': {('numero_cnj', 'user')},
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='usuarios.processo'),
        ),
    ]
