# Generated by Django 6.0.1 on 2026-04-08 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_processo_documentos_processo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_prazo', models.DateField(db_index=True, verbose_name='Data do prazo')),
                ('tipo', models.CharField(choices=[('audiencia', 'Audiência'), ('protocolo', 'Protocolo'), ('recurso', 'Recurso'), ('diligencia', 'Diligência'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('alerta_dias_antes', models.PositiveSmallIntegerField(default=3, verbose_name='Alertar X dias antes')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='ID do evento no Google Calendar')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='usuarios.processo', verbose_name='Processo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to=settings.AUTH_USER_MODEL, verbose_name='Advogado')),
            ],
            options={
                'verbose_name': 'Prazo',
                'verbose_name_plural': 'Prazos',
                'ordering': ['data_prazo'],
            },
        ),
    ]
