# Generated by Django 6.0.1 on 2026-04-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='ultima_consulta_datajud',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta DataJud'),
        ),
        migrations.CreateModel(
            name='AndamentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(blank=True, max_length=200, verbose_name='Tipo')),
                ('codigo_datajud', models.IntegerField(blank=True, null=True, verbose_name='Código DataJud')),
                ('fonte', models.CharField(choices=[('datajud', 'DataJud'), ('manual', 'Manual')], default='datajud', max_length=10, verbose_name='Fonte')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='usuarios.processo')),
            ],
            options={
                'verbose_name': 'Andamento',
                'verbose_name_plural': 'Andamentos',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
