# Generated by Django 6.0.1 on 2026-04-09 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_processo_ultima_consulta_datajud_andamentoprocesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor total (R$)')),
                ('tipo', models.CharField(choices=[('fixo', 'Fixo'), ('exito', 'Êxito'), ('hora', 'Por Hora'), ('mensalidade', 'Mensalidade')], max_length=15, verbose_name='Tipo')),
                ('vencimento', models.DateField(db_index=True, verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to='usuarios.cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honorarios', to='usuarios.processo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Honorário',
                'verbose_name_plural': 'Honorários',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor pago (R$)')),
                ('data_pagamento', models.DateField(verbose_name='Data do pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('honorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='usuarios.honorario')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
