# Generated by Django 6.0.1 on 2026-04-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_honorario_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='telefone_advogado',
            field=models.CharField(blank=True, help_text='DDD + número, sem espaços (ex: 11999999999). Usado para receber alertas.', max_length=20, verbose_name='Seu número WhatsApp'),
        ),
    ]
