# Generated by Django 6.0.1 on 2026-04-10 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TEMPLATES_PADRAO = [
    {
        'nome': 'Contrato de Honorários',
        'tipo': 'contrato',
        'conteudo_markdown': """\
# CONTRATO DE PRESTAÇÃO DE SERVIÇOS ADVOCATÍCIOS

**Contratante:** {{cliente.nome}}
**E-mail:** {{cliente.email}}
**Advogado(a) Contratado(a):** {{advogado.nome}}
**Data:** {{data_hoje}}

---

## CLÁUSULA 1ª — DO OBJETO

O(A) CONTRATANTE contrata os serviços advocatícios do(a) CONTRATADO(A) para representação
judicial e/ou extrajudicial no processo nº {{processo.numero}}, em trâmite perante a
{{processo.vara}} da Comarca de {{processo.comarca}}, bem como em todos os atos necessários
à defesa dos interesses do(a) CONTRATANTE.

## CLÁUSULA 2ª — DOS HONORÁRIOS

Os honorários advocatícios ficam ajustados no valor de **R$ {{honorario.valor}}**, a serem
pagos conforme acordado entre as partes.

## CLÁUSULA 3ª — DA VIGÊNCIA

O presente contrato vigorará pelo prazo necessário à conclusão dos serviços contratados,
podendo ser rescindido por qualquer das partes mediante notificação prévia de 15 (quinze) dias.

## CLÁUSULA 4ª — DO FORO

As partes elegem o foro da Comarca de {{processo.comarca}} para dirimir eventuais conflitos
oriundos do presente contrato.

---

{{processo.comarca}}, {{data_hoje}}.

___________________________
**{{cliente.nome}}**
Contratante

___________________________
**{{advogado.nome}}**
OAB/__ nº ______
Contratado(a)""",
    },
    {
        'nome': 'Procuração Ad Judicia',
        'tipo': 'procuracao',
        'conteudo_markdown': """\
# PROCURAÇÃO AD JUDICIA ET EXTRA

**OUTORGANTE:** {{cliente.nome}}, e-mail {{cliente.email}}.

**OUTORGADO(A):** {{advogado.nome}}, advogado(a) inscrito(a) na Ordem dos Advogados
do Brasil sob o nº ______, com escritório profissional situado em ______.

---

Pelo presente instrumento particular de procuração, o(a) OUTORGANTE nomeia e constitui
seu(sua) bastante procurador(a) o(a) OUTORGADO(A), a quem confere amplos poderes para
o foro em geral, com a cláusula **AD JUDICIA ET EXTRA**, em qualquer Juízo, Instância
ou Tribunal, podendo propor contra quem de direito as ações competentes e defender-se
das que contra si forem propostas, reconvir, agir, contestar, impugnar, transigir,
desistir, receber e dar quitação, firmar compromisso, substabelecer com ou sem reservas,
e praticar todos os demais atos necessários ao fiel cumprimento deste mandato.

Os poderes ora concedidos destinam-se especialmente para representação no processo
nº {{processo.numero}}, em trâmite perante a {{processo.vara}} da Comarca de {{processo.comarca}}.

---

{{processo.comarca}}, {{data_hoje}}.

___________________________
**{{cliente.nome}}**
Outorgante""",
    },
    {
        'nome': 'Notificação Extrajudicial',
        'tipo': 'notificacao',
        'conteudo_markdown': """\
# NOTIFICAÇÃO EXTRAJUDICIAL

**De:** {{advogado.nome}}, advogado(a), em nome de {{cliente.nome}}
**Para:** [NOME DO NOTIFICADO]
**Data:** {{data_hoje}}

---

Venho, na qualidade de advogado(a) constituído(a) por {{cliente.nome}}, notificá-lo(a)
formalmente acerca dos seguintes fatos e direitos:

## I. DOS FATOS

[Descreva os fatos que originaram esta notificação.]

## II. DO DIREITO

[Fundamente juridicamente a notificação.]

## III. DA EXIGÊNCIA

Diante do exposto, fica V.Sa. **NOTIFICADO(A)** a, no prazo de **15 (quinze) dias**
corridos a contar do recebimento desta, [descreva a exigência], sob pena de adoção das
medidas judiciais cabíveis na {{processo.vara}} da Comarca de {{processo.comarca}}.

## IV. ADVERTÊNCIA

O não atendimento desta notificação implicará a adoção imediata de providências judiciais
e extrajudiciais, com apuração de perdas e danos, honorários e custas processuais.

---

{{processo.comarca}}, {{data_hoje}}.

___________________________
**{{advogado.nome}}**
OAB/__ nº ______
Advogado(a) de {{cliente.nome}}""",
    },
    {
        'nome': 'Acordo Extrajudicial',
        'tipo': 'acordo',
        'conteudo_markdown': """\
# ACORDO EXTRAJUDICIAL

**PARTE 1:** {{cliente.nome}}, e-mail {{cliente.email}}
**PARTE 2:** [NOME DA OUTRA PARTE]
**Data:** {{data_hoje}}
**Referência:** {{processo.numero}}

---

As partes, de comum acordo e de livre e espontânea vontade, celebram o presente
**ACORDO EXTRAJUDICIAL** mediante as seguintes cláusulas:

## CLÁUSULA 1ª — DO OBJETO

Resolução amigável da controvérsia relacionada ao processo nº {{processo.numero}},
em trâmite na {{processo.vara}} da Comarca de {{processo.comarca}}.

## CLÁUSULA 2ª — DAS OBRIGAÇÕES

**A PARTE 2 se compromete a:**
1. [Obrigação 1]
2. [Obrigação 2]

**A PARTE 1 se compromete a:**
1. [Contrapartida, se houver]

## CLÁUSULA 3ª — DO VALOR E PAGAMENTO

Valor total acordado: **R$ {{honorario.valor}}**.

[Descreva as condições de pagamento.]

## CLÁUSULA 4ª — DA QUITAÇÃO

Cumpridas as obrigações, as partes darão mútua e recíproca quitação, nada mais
tendo a reclamar a qualquer título.

## CLÁUSULA 5ª — DO FORO

Elegem o foro da Comarca de {{processo.comarca}} para eventuais conflitos.

---

{{processo.comarca}}, {{data_hoje}}.

___________________________         ___________________________
**{{cliente.nome}}**                 [NOME DA OUTRA PARTE]
Parte 1                              Parte 2

___________________________
**{{advogado.nome}}** — OAB/__ nº ______
Advogado(a) Testemunha""",
    },
    {
        'nome': 'Petição Inicial Genérica',
        'tipo': 'peticao',
        'conteudo_markdown': """\
# PETIÇÃO INICIAL

**Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito**
**{{processo.vara}} — Comarca de {{processo.comarca}}**

---

**{{cliente.nome}}**, vem, por intermédio de seu(sua) advogado(a) abaixo assinado(a),
propor a presente

## [TIPO DE AÇÃO]

em face de **[NOME DO RÉU]**, pelos fatos e fundamentos a seguir:

---

## I. DOS FATOS

[Descreva os fatos de forma clara, objetiva e cronológica.]

## II. DO DIREITO

[Fundamente juridicamente o pedido com dispositivos legais e jurisprudência.]

## III. DOS PEDIDOS

Requer o(a) autor(a):

1. A **citação** do(a) réu(ré) para, querendo, contestar a presente ação;
2. A **procedência total** dos pedidos;
3. [Pedido específico 1];
4. [Pedido específico 2];
5. A condenação do(a) réu(ré) ao pagamento de custas e honorários advocatícios
   (art. 85, CPC).

## IV. DO VALOR DA CAUSA

Atribui-se à causa o valor de **R$ {{honorario.valor}}** (art. 291, CPC).

## V. DAS PROVAS

O(A) autor(a) pretende provar os fatos por todos os meios de prova admitidos em
direito, especialmente documental, testemunhal e pericial.

---

Nestes termos, pede deferimento.

{{processo.comarca}}, {{data_hoje}}.

___________________________
**{{advogado.nome}}**
OAB/__ nº ______""",
    },
]


def popular_templates(apps, schema_editor):
    TemplateDocumento = apps.get_model('usuarios', 'TemplateDocumento')
    for t in TEMPLATES_PADRAO:
        TemplateDocumento.objects.get_or_create(
            nome=t['nome'],
            is_global=True,
            user=None,
            defaults={
                'tipo': t['tipo'],
                'conteudo_markdown': t['conteudo_markdown'],
            },
        )


def remover_templates(apps, schema_editor):
    TemplateDocumento = apps.get_model('usuarios', 'TemplateDocumento')
    TemplateDocumento.objects.filter(is_global=True, user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_configuracaowhatsapp_telefone_advogado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do template')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de Honorários'), ('procuracao', 'Procuração'), ('notificacao', 'Notificação Extrajudicial'), ('acordo', 'Acordo Extrajudicial'), ('peticao', 'Petição'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('conteudo_markdown', models.TextField(verbose_name='Conteúdo (Markdown)')),
                ('is_global', models.BooleanField(default=False, verbose_name='Template global (padrão do sistema)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_documento', to=settings.AUTH_USER_MODEL, verbose_name='Advogado')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo gerado')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções adicionais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='usuarios.cliente', verbose_name='Cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='usuarios.processo', verbose_name='Processo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Advogado')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='usuarios.templatedocumento', verbose_name='Template utilizado')),
            ],
            options={
                'verbose_name': 'Documento Gerado',
                'verbose_name_plural': 'Documentos Gerados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RunPython(popular_templates, remover_templates),
    ]
