# Generated by Django 6.0.1 on 2026-04-11 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_templatedocumento_documentogerado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('site', 'Site'), ('outro', 'Outro')], default='outro', max_length=15, verbose_name='Origem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('qualificado', 'Qualificado'), ('proposta', 'Proposta Enviada'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], default='novo', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Advogado')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
            },
        ),
    ]
