# Generated by Django 6.0.1 on 2026-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_cliente_telefone_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ipca_e', 'IPCA-E'), ('inpc', 'INPC'), ('selic', 'SELIC'), ('tr', 'TR'), ('igpm', 'IGP-M'), ('taxa_legal', 'Taxa Legal')], max_length=15)),
                ('data', models.DateField(verbose_name='Mês de referência')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Variação mensal (%)')),
                ('fonte', models.CharField(choices=[('bcb', 'Banco Central'), ('ibge', 'IBGE'), ('tjsp', 'TJSP')], default='bcb', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Índice Econômico',
                'verbose_name_plural': 'Índices Econômicos',
                'ordering': ['-data', 'tipo'],
                'unique_together': {('tipo', 'data')},
            },
        ),
    ]
