# Generated by Django 6.0.1 on 2026-05-13 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_indiceeconomico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição do cálculo')),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor principal (R$)')),
                ('data_inicio', models.DateField(verbose_name='Data do fato gerador')),
                ('data_fim', models.DateField(verbose_name='Data do cálculo')),
                ('indice_correcao', models.CharField(choices=[('ipca_e', 'IPCA-E'), ('inpc', 'INPC'), ('selic', 'SELIC'), ('tr', 'TR'), ('igpm', 'IGP-M'), ('taxa_legal', 'Taxa Legal')], default='ipca_e', max_length=15, verbose_name='Índice de correção')),
                ('juros_tipo', models.CharField(choices=[('simples_1', 'Juros simples 1% a.m.'), ('simples_05', 'Juros simples 0,5% a.m.'), ('selic', 'SELIC integral'), ('taxa_legal', 'Taxa Legal (Lei 14.905/2024)'), ('customizado', 'Percentual customizado')], default='simples_1', max_length=15, verbose_name='Tipo de juros')),
                ('juros_percentual', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Juros % a.m.')),
                ('multa_523', models.BooleanField(default=False, verbose_name='Multa Art. 523 CPC (10%)')),
                ('honorarios_sucumb', models.BooleanField(default=False, verbose_name='Honorários sucumbenciais')),
                ('honorarios_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Honorários %')),
                ('resultado_json', models.JSONField(blank=True, null=True, verbose_name='Resultado detalhado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos', to='usuarios.processo', verbose_name='Processo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_judiciais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo Judicial',
                'verbose_name_plural': 'Cálculos Judiciais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
