# Generated by Django 6.0.1 on 2026-06-13 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_calculojudicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_externos', to='usuarios.processo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link do Processo',
                'verbose_name_plural': 'Links dos Processos',
                'ordering': ['titulo'],
            },
        ),
    ]
