# Generated by Django 6.0.1 on 2026-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_linkprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculojudicial',
            name='marco_inicial_observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observação do marco inicial'),
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='marco_inicial_tipo',
            field=models.CharField(choices=[('fato_gerador', 'Data do fato gerador'), ('citacao', 'Recebimento da citação'), ('sentenca', 'Sentença'), ('publicacao', 'Publicação/certificação'), ('transito_julgado', 'Trânsito em julgado'), ('customizado', 'Data customizada')], default='fato_gerador', max_length=20, verbose_name='Marco inicial'),
        ),
    ]
